# Generated by Django 5.1 on 2024-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="static/files/"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
